### ISSUE TITLE
You must supply a name when declaring a directory resource

### ISSUE THREAD

**Issue by lioramilbaum** [chef-cookbooks/ark#173]
### Cookbook version
2.1.0
### Chef-client version
12.16.42

### Platform Details
Windows 2012 - Softlayer

### Scenario:
deploy nodejs via nodejs cookbook

### Steps to Reproduce:
This is my recipe

```
include_recipe 'git'
include_recipe 'nodejs'
include_recipe 'nodejs::npm'
```

### Actual Result:
```
169.46.88.67 [2016-11-21T13:46:13-06:00] INFO: Processing ark[nodejs-source] action install_with_make (nodejs::nodejs_from_source line 49)
169.46.88.67 
169.46.88.67 
169.46.88.67 ================================================================================
169.46.88.67 Error executing action `install_with_make` on resource 'ark[nodejs-source]'
169.46.88.67 ================================================================================
169.46.88.67 
169.46.88.67 ArgumentError
169.46.88.67 -------------
169.46.88.67 You must supply a name when declaring a directory resource
169.46.88.67 
169.46.88.67 Cookbook Trace:
169.46.88.67 ---------------
169.46.88.67 c:/chef/cache/cookbooks/ark/providers/default.rb:261:in `block in class_from_file'
169.46.88.67 
169.46.88.67 Resource Declaration:
169.46.88.67 ---------------------
169.46.88.67 # In c:/chef/cache/cookbooks/nodejs/recipes/nodejs_from_source.rb
169.46.88.67 
169.46.88.67  49: ark archive_name do
169.46.88.67  50:   url nodejs_src_url
169.46.88.67  51:   version node['nodejs']['version']
169.46.88.67  52:   checksum node['nodejs']['source']['checksum']
169.46.88.67  53:   make_opts ["-j #{node['nodejs']['make_threads']}"]
169.46.88.67  54:   action :install_with_make
169.46.88.67  55: end
169.46.88.67 
169.46.88.67 Compiled Resource:
169.46.88.67 ------------------
169.46.88.67 # Declared in c:/chef/cache/cookbooks/nodejs/recipes/nodejs_from_source.rb:49:in `from_file'
169.46.88.67 
169.46.88.67 ark("nodejs-source") do
169.46.88.67   action [:install_with_make]
169.46.88.67   retries 0
169.46.88.67   retry_delay 2
169.46.88.67   default_guard_interpreter :default
169.46.88.67   declared_type :ark
169.46.88.67   cookbook_name "nodejs"
169.46.88.67   recipe_name "nodejs_from_source"
169.46.88.67   url "https://nodejs.org/dist/v6.9.1/node-v6.9.1.tar.xz"
169.46.88.67   version "6.9.1"
169.46.88.67   checksum "0bdd8d1305777cc8cd206129ea494d6c6ce56001868dd80147aff531d6df0729"
169.46.88.67   make_opts ["-j 8"]
169.46.88.67   extension "tar.xz"
169.46.88.67   prefix_bin "/usr/local/bin"
169.46.88.67   prefix_root "/usr/local"
169.46.88.67   home_dir "/usr/local/nodejs-source"
169.46.88.67   release_file "c:/chef/cache/nodejs-source-6.9.1.tar.xz"
169.46.88.67 end
169.46.88.67 
169.46.88.67 Platform:
169.46.88.67 ---------
169.46.88.67 x64-mingw32
169.46.88.67 
169.46.88.67 
169.46.88.67 [2016-11-21T13:46:13-06:00] INFO: Running queued delayed notifications before re-raising exception
169.46.88.67 [2016-11-21T13:46:13-06:00] ERROR: Running exception handlers
169.46.88.67 [2016-11-21T13:46:13-06:00] ERROR: Exception handlers complete
169.46.88.67 [2016-11-21T13:46:13-06:00] INFO: Sending resource update report (run-id: 27eead08-3089-4a97-b8d4-3a9ba223118d)
169.46.88.67 [2016-11-21T13:46:13-06:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
169.46.88.67 [2016-11-21T13:46:13-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
169.46.88.67 [2016-11-21T13:46:13-06:00] FATAL: ArgumentError: ark[nodejs-source] (nodejs::nodejs_from_source line 49) had an error: ArgumentError: You must supply a name when declaring a directory resource
ERROR: Failed to execute command on 169.46.88.67 return code 1
```

**Comment by cheeseplus** [comment]
The issue here is that the upstream cookbook doesn't support Windows.

Closing.
