### ISSUE TITLE
OS X broken > 2.0.0

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/ark#175]
### Cookbook version
2.0.1 / 2.0.2 & 2.1.0

### Chef-client version
12.16.42

### Platform Details
OSX 10.11 & OSX 10.12

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
Converge an OSX box will result in an error on the following line:
21>> package node['ark']['package_dependencies'] unless node['platform_family'] == 'windows'
in default.rb

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/XXXXXX_base/recipes/default.rb
       ================================================================================
       
       ArgumentError
       -------------
       You must supply a name when declaring a package resource
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/ark/recipes/default.rb:21:in `from_file'
         /tmp/kitchen/cache/cookbooks/XXXXXX_base/recipes/default.rb:12:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/ark/recipes/default.rb:
       
        14:  # Unless required by applicable law or agreed to in writing, software
        15:  # distributed under the License is distributed on an "AS IS" BASIS,
        16:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        17:  # See the License for the specific language governing permissions and
        18:  # limitations under the License.
        19:  #
        20:  
        21>> package node['ark']['package_dependencies'] unless node['platform_family'] == 'windows'
        22:  
        23:  include_recipe 'seven_zip' if node['platform_family'] == 'windows'
        24:  
       
       Platform:
       ---------
       x86_64-darwin13
       
       
       Running handlers:
       [2016-12-06T14:19:54-08:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-12-06T14:19:54-08:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 04 seconds

**Comment by Sauraus** [comment]
Fixed by: https://github.com/chef-cookbooks/ark/pull/176
