### ISSUE TITLE
Don't know how to expand https://bintray.com/jfrog/artifactory/download_file?file_path=jfrog-artifactory-oss-5.9.0.zip

### ISSUE THREAD

**Issue by scalp42** [chef-cookbooks/ark#202]
### Cookbook version

`ark@3.1.0`

### Chef-client version

`Chef: 13.8.3`

### Platform Details

`Ubuntu 16.04`

### Scenario:

Trying to extract [Artifactory OSS zip](https://bintray.com/jfrog/artifactory/jfrog-artifactory-oss-zip)

### Steps to Reproduce:

```ruby
ark %|Artifactory| do
  url 'https://bintray.com/jfrog/artifactory/download_file?file_path=jfrog-artifactory-oss-5.9.0.zip'
  version '5.9.0'
  path '/opt/artifactory'
  append_env_path true
  backup 5
  action :put
end
```
### Actual Result:

```
[2018-03-06T02:05:30+00:00] ERROR: ark[Artifactory 5.9.0] (iad-artifactory::default line 24) had an error: RuntimeError: Don't know how to expand https://bintray.com/jfrog/artifactory/download_file?file_path=jfrog-artifactory-oss-5.9.0.zip (extension: )
```

I'm assuming the `?` in the url might be culprit.

**Comment by scalp42** [comment]
Stacktrace:

```
root@default-ubuntu-1604:~# cat /tmp/kitchen/cache/chef-stacktrace.out
Generated at 2018-03-06 02:05:30 +0000
RuntimeError: ark[Artifactory 5.9.0] (iad-artifactory::default line 24) had an error: RuntimeError: Don't know how to expand https://bintray.com/jfrog/artifactory/download_file?file_path=jfrog-artifactory-oss-5.9.0.zip (extension: )
/tmp/kitchen/cache/cookbooks/ark/libraries/tar_command_builder.rb:44:in `args'
/tmp/kitchen/cache/cookbooks/ark/libraries/tar_command_builder.rb:4:in `unpack'
/tmp/kitchen/cache/cookbooks/ark/libraries/default.rb:79:in `unpack_command'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.3/lib/chef/resource.rb:1295:in `method_missing'
/tmp/kitchen/cache/cookbooks/ark/resources/default.rb:149:in `block (2 levels) in class_from_file'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.3/lib/chef/resource_builder.rb:66:in `instance_eval'
```

**Comment by scalp42** [comment]
Workaround if anyone finds this:

Specify `extension 'zip'` in the ark resource by hand.
